
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: jungle_development
  # username: development
  # password: development
  min_messages: notice

test:
  <<: *default
  database: jungle_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>